# Build settings
markdown: redcarpet
highlighter: pygments

# URL pattern
permalink: /:year/:title/

# Site settings
title: "Blog of Pesh"
description: > # this means to ignore newlines until "email:"
   Er du som meg - så er dette interessant

email: perandre@gmail.com
#blog logo
logo: "/assets/images/perandre-logo.jpg"
# blog cover
cover: "/assets/images/skrivemaskin.jpg"

name: 'Per André Rønsen'
author: 'Per André Rønsen'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://perandre.no" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/perandre
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/perandreronsen
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

# - icon:	github
#   url:	https://github.com/perandre
#   desc:	Fork me on github
#   share_url:
#   share_title:
#   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
